=== Orichievac/FallenGalaxy/src-server/conf/db-mapping.dtd
<!ELEMENT db-mapping (table*)>
<!ATTLIST db-mapping
	package			CDATA ''
>

<!ELEMENT table (column|primary-key|index|foreign-key)*>
<!ATTLIST table
	name			ID #REQUIRED
	class			CDATA #IMPLIED
	package			CDATA #IMPLIED
	cache			(true|false) 'true'
	allow-delete	(true|false) 'true'
>

<!ELEMENT column EMPTY>
<!ATTLIST column
	name			CDATA #REQUIRED
	type			(boolean|byte|short|int|long|float|double|string|timestamp) #IMPLIED
	reftype			CDATA #IMPLIED
	java-type		CDATA #IMPLIED
	db-type			CDATA #IMPLIED
	enum-values		CDATA #IMPLIED
	nullable		(true|false) #IMPLIED
	signed			(true|false) #IMPLIED
>

<!ELEMENT primary-key EMPTY>
<!ATTLIST primary-key
	name			CDATA #REQUIRED
	generator		(none|increment) 'none'
>

<!ELEMENT index EMPTY>
<!ATTLIST index
	name			CDATA #REQUIRED
	type			(unique|multiple) 'unique'
>

<!ELEMENT foreign-key (references)>
<!ATTLIST foreign-key
	name			CDATA #REQUIRED
>

<!ELEMENT references EMPTY>
<!ATTLIST references
	table			IDREF #REQUIRED
	column			CDATA #REQUIRED
	on-delete		(set-null|set-zero|cascade|restrict|no-action) #REQUIRED
>

=== Orichievac/FallenGalaxy/src-server/conf/db-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE db-mapping SYSTEM "db-mapping.dtd">

<db-mapping package="fr.fg.server.data">
	<!-- =============================================== AccountAction ==== -->
	
	<table name="account_action">
		<column name="login"		type="string"/>
		<column name="action"		type="string"	enum-values="registered,closed,idle"/>
		<column name="email"		type="string"/>
		<column name="birthday"		type="long"/>
		<column name="date"			type="long"/>
		<column name="ip"			type="int"/>
		<column name="played_time"	type="long"/>
		<column name="reason"		type="string"/>
		
		<primary-key name="login"/>
	</table>
	
	<!-- ================================================ Achievements ==== -->
	
	<table name="achievement">
		<column name="id_player"	type="int"/>
		<column name="type"			type="int"/>
		<column name="score"		type="long"/>
		
		<primary-key name="id_player"/>
		<primary-key name="type"/>
		
		<foreign-key name="id_player">
			<references table="player" column="id" on-delete="cascade"/>
		</foreign-key>
	</table>
	
	<!-- ================================================= Advancement ==== -->
	
	<table name="advancement">
		<column name="id_player"	type="int"/>
		<column name="type"			type="int"/>
		<column name="level"		type="int"/>
		
		<primary-key name="id_player"/>
		<primary-key name="type"/>
		
		<foreign-key name="id_player">
			<references table="player" column="id" on-delete="cascade"/>
		</foreign-key>
	</table>
	
	<!-- ======================================================== Ally ==== -->
	
	<table name="ally">
		<column name="id"						type="int"		db-type="mediumint" signed="false"/>
		<column name="name"						type="string"/>
		<column name="tag"						type="string"	db-type="char"/>
		<column name="ai"						type="boolean"/>
		<column name="color"					type="int"		db-type="tinyint" signed="false"/>
		<column name="organization"				type="string"	enum-values="tyranny,warmonger,democracy,oligarchy,anarchy"/>
		<column name="description"				type="string"	db-type="text"/>
		<column name="birthdate"				type="long"		db-type="int" signed="false"/>
		<column name="points"					type="long"		signed="false"/>
		<column name="right_accept"				type="int"		db-type="tinyint" signed="false"/>
		<column name="right_manage_news"		type="int"		db-type="tinyint" signed="false"/>
		<column name="right_manage_stations"	type="int"		db-type="tinyint" signed="false"/>
		<column name="right_manage_diplomacy"	type="int"		db-type="tinyint" signed="false"/>
		<column name="right_manage_description"	type="int"		db-type="tinyint" signed="false"/>
		<column name="right_manage_contracts"	type="int"		db-type="tinyint" signed="false"/>
		<column name="id_creator"				type="int"		signed="false"/>
		
		<primary-key name="id" generator="increment"/>
		
		<index name="name"/>
		<index name="tag"/>
		
		<foreign-key name="id_creator">
			<references table="player" column="id" on-delete="set-zero"/>
		</foreign-key>
	</table>
	
	<!-- =============================================== AllyInfluence ==== -->
	
	<table name="ally_influence">
		<column name="id_ally"			type="int"/>
		<column name="id_sector"		type="int"/>
		<column name="influence_coef"	type="double"/>
		<column name="influence_value"	type="int"/>
		<column name="systems_count"	type="int"/>
		
		<primary-key name="id_ally"/>
		<primary-key name="id_sector"/>
		
		<foreign-key name="id_ally">
			<references table="ally" column="id" on-delete="cascade"/>
		</foreign-key>
		<foreign-key name="id_sector">
			<references table="sector" column="id" on-delete="cascade"/>
		</foreign-key>
	</table>
	
	<!-- ==================================================== AllyNews ==== -->
	
	<table name="ally_news">
		<column name="id"			type="int"		signed="false"/>
		<column name="title"		type="string"	db-type="text"/>
		<column name="content"		type="string"/>
		<column name="date"			type="long"		db-type="int" signed="false"/>
		<column name="id_author"	type="int"		db-type="int" signed="false"/>
		<column name="id_vote"		type="int"		db-type="int" signed="false"/>
		<column name="id_election"	type="int"		db-type="int" signed="false"/>
		<column name="id_applicant"	type="int"		db-type="int" signed="false"/>
		<column name="id_ally"		type="int"		db-type="mediumint" signed="false"/>
		<column name="id_parent"	type="int"		db-type="int" signed="false"/>
		<column name="sticky"		type="boolean"/>
		
		<primary-key name="id" generator="increment"/>
		
		<index name="id_ally" type="multiple"/>
		
		<foreign-key name="id_author">
			<references table="player" column="id" on-delete="cascade"/>
		</foreign-key>
		<foreign-key name="id_vote">
			<references table="ally_vote" column="id" on-delete="set-zero"/>
		</foreign-key>
		<foreign-key name="id_election">
			<references table="election" column="id" on-delete="set-zero"/>
		</foreign-key>
		<foreign-key name="id_applicant">
			<references table="player" column="id" on-delete="set-zero"/>
		</foreign-key>
		<foreign-key name="id_ally">
			<references table="ally" column="id" on-delete="cascade"/>
		</foreign-key>
		<foreign-key name="id_parent">
			<references table="ally_news" column="id" on-delete="cascade"/>
		</foreign-key>
	</table>
	
	<!-- ==================================================== AllyNews ==== -->
	
	<table name="ally_news_read">
		<column name="id_ally_news"			type="int"/>
		<column name="id_player"			type="int"/>
		
		<primary-key name="id_ally_news"/>
		<primary-key name="id_player"/>
		
		<foreign-key name="id_ally_news">
			<references table="ally_news" column="id" on-delete="cascade"/>
		</foreign-key>
		<foreign-key name="id_player">
			<references table="player" column="id" on-delete="cascade"/>
		</foreign-key>
	</table>
		
	<!-- ================================================== AllyTreaty ==== -->
	
	<table name="ally_treaty">
		<column name="id_ally1"			type="int"/>
		<column name="id_ally2"			type="int"/>
		<column name="type"				type="string"	enum-values="war,ally,defensive,total"/>
		<column name="date"				type="long"/>
		<column name="last_activity"	type="long"/>
		<column name="source"			type="int"/>
		
		<primary-key name="id_ally1"/>
		<primary-key name="id_ally2"/>
		
		<foreign-key name="id_ally1">
			<references table="ally" column="id" on-delete="cascade"/>
		</foreign-key>
		<foreign-key name="id_ally2">
			<references table="ally" column="id" on-delete="cascade"/>
		</foreign-key>
	</table>
	
	<!-- ==================================================== AllyVote ==== -->
	
	<table name="ally_vote">
		<column name="id"			type="int"/>
		<column name="type"			type="string"	enum-values="accept,kick"/>
		<column name="yes"			type="int"/>
		<column name="no"			type="int"/>
		<column name="date"			type="long"/>
		<column name="id_player"	type="int"/>
		<column name="id_ally"		type="int"/>
		<column name="id_initiator"	type="int"/>
		
		<primary-key name="id" generator="increment"/>
		
		<index name="id_ally" type="multiple"/>
		<index name="id_player"/>
		
		<foreign-key name="id_player">
			<references table="player" column="id" on-delete="cascade"/>
		</foreign-key>
		<foreign-key name="id_ally">
			<references table="ally" column="id" on-delete="cascade"/>
		</foreign-key>
		<foreign-key name="id_initiator">
			<references table="player" column="id" on-delete="set-zero"/>
		</foreign-key>
	</table>
	
	<!-- ==================================================== AllyVoter ==== -->
	
	<table name="ally_voter">
		<column name="id_vote"		type="int"/>
		<column name="id_player"	type="int"/>
		
		<primary-key name="id_vote"/>
		<primary-key name="id_player"/>
		
		<foreign-key name="id_vote">
			<references table="ally_vote" column="id" on-delete="cascade"/>
		</foreign-key>
		<foreign-key name="id_player">
			<references table="player" column="id" on-delete="cascade"/>
		</foreign-key>
	</table>
	
	<!-- =================================================== Applicant ==== -->
	
	<table name="applicant">
		<column name="id_ally"		type="int"/>
		<column name="id_player"	type="int"/>
		<column name="date"			type="long"/>
		
		<primary-key name="id_player"/>
		
		<index name="id_ally" type="multiple"/>
		
		<foreign-key name="id_ally">
			<references table="ally" column="id" on-delete="cascade"/>
		</foreign-key>
		<foreign-key name="id_player">
			<references table="player" column="id" on-delete="cascade"/>
		</foreign-key>
	</table>
	
	<!-- ======================================================== Area ==== -->
	
	<table name="area">
		<column name="id"					type="int"		db-type="smallint" signed="false"/>
		<column name="name"					type="string"	db-type="char"/>
		<column name="width"				type="int"		db-type="smallint" signed="false"/>
		<column name="height"				type="int"		db-type="smallint" signed="false"/>
		<column name="x"					type="int"		db-type="smallint"/>
		<column name="y"					type="int"		db-type="smallint"/>
		<column name="type"					type="int"		db-type="tinyint" signed="false"/>
		<column name="space_stations_limit"	type="int"		db-type="tinyint" signed="false"/>
		<column name="product"				type="int"		db-type="smallint" signed="false"/>
		<column name="full"					type="boolean"/>
		<column name="last_name_update"		type="long"		db-type="int" signed="false"/>
		<column name="id_dominating_ally"	type="int"		signed="false"/>
		<column name="id_sector"			type="int"		db-type="int" signed="false"/>
		<column name="environment"			type="string"	enum-values="normal,glacial,desert,alien,mine,epave"/>
		
		<primary-key name="id" generator="increment"/>
		
		<index name="name"/>
		
		<foreign-key name="id_dominating_ally">
			<references table="ally" column="id" on-delete="set-zero"/>
		</foreign-key>
		<foreign-key name="id_sector">
			<references table="sector" column="id" on-delete="cascade"/>
		</foreign-key>
	</table>
	
	<!-- ======================================================== Bank ==== -->
	
	<table name="bank">
		<column name="id_bank"			type="int"/>
		<column name="base_rate"		type="double"/>
