=== Orichievac/FallenGalaxy/war/WEB-INF/classes/conf/action-mapping.dtd
<!ELEMENT action-mapping (constant*,action*)>
<!ATTLIST action-mapping
	package		CDATA ''
>

<!-- Constant definition -->
<!ELEMENT constant EMPTY>
<!ATTLIST constant
	name        CDATA #REQUIRED
	value       CDATA #REQUIRED
>

<!-- Action definition -->
<!ELEMENT action (action-param)*>
<!ATTLIST action
	name        CDATA #REQUIRED
	class       CDATA #REQUIRED
	method      (get|post) "post"
	rights		CDATA #IMPLIED
	connection	(login|logout|login_or_logout) "login"
>

<!-- Action parameter definition -->
<!ELEMENT action-param (param-format)*>
<!ATTLIST action-param
	name        CDATA #REQUIRED
	required    (false|true) "true"
>

<!-- Parameter format definition -->
<!ELEMENT param-format (arg)*>
<!ATTLIST param-format
	class       CDATA #REQUIRED
>

<!-- Format arguments definition -->
<!ELEMENT arg EMPTY>
<!ATTLIST arg
	value       CDATA #REQUIRED
>

=== Orichievac/FallenGalaxy/war/WEB-INF/classes/conf/action-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE action-mapping SYSTEM "action-mapping.dtd">

<action-mapping package="fr.fg.server.action">
	<!-- ================================================== CONSTANTES ==== -->
	
	<!-- Formats -->
	<constant name="formatPath"     	value="fr.fg.server.servlet.format"/>
	<constant name="boolean"        	value="${formatPath}.BooleanFormat"/>
	<constant name="enum"           	value="${formatPath}.EnumFormat"/>
	<constant name="int"            	value="${formatPath}.IntegerFormat"/>
	<constant name="intRange"       	value="${formatPath}.IntegerRangeFormat"/>
	<constant name="long"            	value="${formatPath}.LongFormat"/>
	<constant name="longRange"       	value="${formatPath}.LongRangeFormat"/>
	<constant name="string"         	value="${formatPath}.StringFormat"/>
	<constant name="stringRange"    	value="${formatPath}.SizedStringFormat"/>
	<constant name="name"				value="${formatPath}.NameStringFormat"/>
	<constant name="wildcardname"		value="${formatPath}.WildcardNameStringFormat"/>
	<constant name="alphabetic"			value="${formatPath}.AlphabeticFormat"/>
	<constant name="email"				value="${formatPath}.EmailStringFormat"/>
	
	<!-- Constantes des formats -->
	<constant name="superiorEqual"  	value="1"/>
	<constant name="inferiorEqual"  	value="2"/>
	<constant name="between"        	value="3"/>
	<constant name="notEqual"       	value="4"/>
	
	<!-- Droits d'accès -->
	<constant name="user"					value="0"/>
	<constant name="premium"				value="1"/>
	<constant name="moderator"				value="2"/>
	<constant name="premium+moderator"		value="3"/>
	<constant name="administrator"			value="4"/>
	<constant name="premium+administrator"	value="5"/>
	<constant name="super_administrator"	value="8"/>
	
	<!-- ===================================================== ACTIONS ==== -->
	
	<!-- Déconnexion du jeu -->
	<action name="initialization" class="login.Initialization" connection="login_or_logout"/>
	
	<!-- Connexion au jeu -->
	<action name="login" class="login.LogIn" connection="logout">
		<action-param name="login">
			<param-format class="name"/>
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="4"/>
				<arg value="30"/>
			</param-format>
		</action-param>
		<action-param name="password">
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="4"/>
				<arg value="50"/>
			</param-format>
		</action-param>
	</action>
	
	<action name="closeaccount" class="player.CloseAccount">
		<action-param name="password">
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="4"/>
				<arg value="50"/>
			</param-format>
		</action-param>
		<action-param name="reason">
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="0"/>
				<arg value="250"/>
			</param-format>
		</action-param>
	</action>
	
	<!-- Connexion au jeu -->
	<action name="getfirstsystem" class="login.GetFirstSystem">
		<action-param name="near">
			<param-format class="name"/>
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="0"/>
				<arg value="30"/>
			</param-format>
		</action-param>
	</action>
	
	<!-- Déconnexion du jeu -->
	<action name="logout" class="login.LogOut"/>
	
	<!-- Inscription d'un nouveau joueur -->
	<action name="register" class="login.Register" connection="logout">
		<action-param name="login">
			<param-format class="name"/>
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="4"/>
				<arg value="20"/>
			</param-format>
		</action-param>
		<action-param name="password">
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="4"/>
				<arg value="50"/>
			</param-format>
		</action-param>
		<action-param name="email">
			<param-format class="email"/>
		</action-param>
		<action-param name="birthday">
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="0"/>
				<arg value="10"/>
			</param-format>
		</action-param>
		<action-param name="sponsor">
			<param-format class="name"/>
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="0"/>
				<arg value="20"/>
			</param-format>
		</action-param>
	</action>
	
	<action name="killpolling" class="KillPolling"/>
	
	   <action name="setaway" class="player.SetAway">
                <action-param name="away">
                        <param-format class="boolean"/>
                </action-param>
        </action>
	
	<!-- Récupération du mot de passe -->
	<action name="recoverpassword" class="login.RecoverPassword" connection="logout">
		<action-param name="email">
			<param-format class="email"/>
		</action-param>
	</action>
	
	<action name="getarea" class="GetArea">
		<action-param name="area">
			<param-format class="intRange">
				<arg value="superiorEqual"/>
				<arg value="1"/>
			</param-format>
		</action-param>
	</action>
	
	<action name="setareaname" class="SetAreaName">
		<action-param name="area">
			<param-format class="intRange">
				<arg value="superiorEqual"/>
				<arg value="1"/>
			</param-format>
		</action-param>
		<action-param name="name">
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="4"/>
				<arg value="20"/>
			</param-format>
			<param-format class="name"/>
		</action-param>
	</action>
	
	<action name="getgalaxy" class="GetGalaxy"/>
	
	<!-- Récupération  d'un rapport de combat -->
	<action name="getreport" class="GetReport">
		<action-param name="report">
			<param-format class="intRange">
				<arg value="superiorEqual"/>
				<arg value="1"/>
			</param-format>
		</action-param>
	</action>
	
	<!-- Récupération  d'un rapport de combat par son code de hashage -->
	<action name="getreportbyhash" class="GetReportByHash" connection="login_or_logout">
		<action-param name="hash">
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="16"/>
				<arg value="16"/>
			</param-format>
		</action-param>
	</action>
	
	<!-- Demande de mise à jour -->
	<action name="update" class="player.Update">
		<action-param name="type">
			<param-format class="enum">
				<arg value="fleets+area"/>
				<arg value="xp"/>
				<arg value="systems"/>
			</param-format>
		</action-param>
	</action>
	
	<!-- Obtenir le nom du serveur -->
	<action name="serverinfos" class="GetServerInfos" connection="login_or_logout" />
	
	<!-- ===================================================== PREMIUM ==== -->
	
	<action name="premium/getstate" class="premium.GetPremiumState"/>
	
	<action name="premium/validatecode" class="premium.ValidateCode">
		<action-param name="code">
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="1"/>
				<arg value="10"/>
			</param-format>
		</action-param>
	</action>
	
	<!-- ===================================================== MARKERS ==== -->
	
	<action name="markers/add" class="markers.CreateMarker">
		<action-param name="area">
			<param-format class="intRange">
				<arg value="superiorEqual"/>
				<arg value="1"/>
			</param-format>
		</action-param>
		<action-param name="x">
			<param-format class="intRange">
				<arg value="superiorEqual"/>
				<arg value="0"/>
			</param-format>
		</action-param>
		<action-param name="y">
			<param-format class="intRange">
				<arg value="superiorEqual"/>
				<arg value="0"/>
			</param-format>
		</action-param>
		<action-param name="message">
			<param-format class="stringRange">
				<arg value="between"/>
				<arg value="4"/>
				<arg value="200"/>
			</param-format>
		</action-param>
		<action-param name="visibility">
			<param-format class="enum">
				<arg value="player"/>
				<arg value="ally"/>
				<arg value="allied"/>
			</param-format>
		</action-param>
		<action-param name="galaxy">
			<param-format class="boolean"/>
		</action-param>
	</action>
	
	<action name="markers/delete" class="markers.DeleteMarker">
		<action-param name="marker">
			<param-format class="intRange">
				<arg value="superiorEqual"/>
				<arg value="1"/>
			</param-format>
		</action-param>
	</action>
	
	<!-- ==================================================== CONTRACT ==== -->
	
	<action name="contracts/get" class="contract.GetContracts"/>
	
	<action name="contracts/apply" class="contract.Apply">
		<action-param name="id">
			<param-format class="longRange">
				<arg value="superiorEqual"/>
				<arg value="1"/>
			</param-format>
		</action-param>
	</action>
	
	<action name="contracts/decline" class="contract.Decline">
		<action-param name="id">
			<param-format class="longRange">
				<arg value="superiorEqual"/>
				<arg value="1"/>
			</param-format>
		</action-param>
	</action>
	
	<action name="contracts/giveup" class="contract.GiveUp">
		<action-param name="id">
			<param-format class="longRange">
				<arg value="superiorEqual"/>
				<arg value="1"/>
			</param-format>
		</action-param>
	</action>
	
	<!-- ======================================================== BANK ==== -->
	
	<action name="bank/getaccount" class="bank.GetAccount">
		<action-param name="fleet">
			<param-format class="intRange">
				<arg value="superiorEqual"/>
				<arg value="1"/>
			</param-format>
		</action-param>
	</action>
	
	<action name="bank/transfer" class="bank.Transfer">
		<action-param name="fleet">
			<param-format class="intRange">
				<arg value="superiorEqual"/>
				<arg value="1"/>
			</param-format>
		</action-param>
		<action-param name="resource0">
			<param-format class="longRange">
				<arg value="superiorEqual"/>
				<arg value="0"/>
			</param-format>
		</action-param>
		<action-param name="resource1">
			<param-format class="longRange">
				<arg value="superiorEqual"/>
				<arg value="0"/>
			</param-format>
		</action-param>
		<action-param name="resource2">
			<param-format class="longRange">
				<arg value="superiorEqual"/>
				<arg value="0"/>
			</param-format>
		</action-param>
		<action-param name="resource3">
			<param-format class="longRange">
				<arg value="superiorEqual"/>
				<arg value="0"/>
