=== Orichievac/FallenGalaxy/src-server/fr/fg/server/contract/dialog/dialogs.dtd
<!ENTITY init "init">
<!ENTITY eod "EOD">

<!ELEMENT dialogs (key*,dialog*)>

<!ELEMENT key EMPTY>
<!ATTLIST key
	name		CDATA #REQUIRED
	value		CDATA #REQUIRED
>

<!ELEMENT dialog (entry+)>
<!ATTLIST dialog
	type		ID	#REQUIRED
>

<!ELEMENT entry (option+)>
<!ATTLIST entry
	name		CDATA #REQUIRED
>

<!ELEMENT option EMPTY>
<!ATTLIST option
	target		CDATA #REQUIRED
	condition	CDATA #IMPLIED
>

=== Orichievac/FallenGalaxy/war/WEB-INF/classes/fr/fg/server/contract/impl/BuildShips.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogs SYSTEM "../dialog/dialogs.dtd">

<dialogs>
	<key name="shipName" value="getShipNameToDeliver"/>
	<key name="shipCount" value="getShipsCountFleetMayDeliver"/>
	<key name="iconXp" value="getXpImg"/>
	
	<dialog type="recipientWaiting">
		<entry name="&init;">
			<option target="transfer" condition="mayFleetDeliverShips"/>
			<option target="hurryUp"/>
		</entry>
		<entry name="transfer">
			<option target="&eod;"/>
		</entry>
		<entry name="hurryUp">
			<option target="&eod;"/>
		</entry>
	</dialog>
	
	<dialog type="recipientDelivered">
		<entry name="&init;">
			<option target="&eod;"/>
		</entry>
	</dialog>
	
	<dialog type="recipientReward">
		<entry name="&init;">
			<option target="&eod;"/>
		</entry>
	</dialog>
</dialogs>

=== Orichievac/FallenGalaxy/src-server/fr/fg/server/contract/impl/BuildWards.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dialogs SYSTEM "../dialog/dialogs.dtd">

<dialogs>
	<key name="xp" value="getFleetXpReward"/>
	<key name="iconXp" value="getXpImg"/>
	
	<dialog type="reward">
		<entry name="&init;">
			<option target="what"/>
			<option target="fastReward"/>
		</entry>
		
		<entry name="what">
			<option target="reward"/>
		</entry>
		
		<entry name="reward">
			<option target="update" condition="mayFleetGetReward"/>
			<option target="cancel"/>
		</entry>
		
		<entry name="fastReward">
			<option target="update" condition="mayFleetGetReward"/>
			<option target="cancel"/>
		</entry>
		
		<entry name="update">
			<option target="&eod;"/>
		</entry>
		
		<entry name="cancel">
			<option target="&eod;"/>
		</entry>
	</dialog>
</dialogs>
